" Generated by theme pipeline. Keep this file minimal and deterministic.
hi clear
if exists("syntax_on")
  syntax reset
endif

set background=dark

hi Normal       guifg={{ foreground }} guibg={{ background }} ctermfg=15 ctermbg=0
hi NormalNC     guifg={{ foreground }} guibg={{ background }} ctermfg=15 ctermbg=0
hi CursorLine   guibg={{ color0 }} ctermbg=0
hi LineNr       guifg={{ color8 }} ctermbg=NONE
hi CursorLineNr guifg={{ accent }} ctermfg=4 cterm=bold
hi Visual       guifg={{ selection_foreground }} guibg={{ selection_background }} cterm=reverse
hi Pmenu        guifg={{ foreground }} guibg={{ color0 }}
hi PmenuSel     guifg={{ background }} guibg={{ accent }}
hi StatusLine   guifg={{ foreground }} guibg={{ color0 }}
hi StatusLineNC guifg={{ color8 }} guibg={{ color0 }}
