#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

mpv --volume=60 'Microsoft Windows 95 Startup Sound-miZHa7ZC6Z0.m4a' &

xrandr --output HDMI2 --off &
# xrandr --output HDMI2 --same-as eDP1 --mode 1366x768 &

#feh --randomize --recursive --bg-fill /home/langest/img/wps
feh --randomize --recursive --bg-tile /home/langest/img/tiling

redshift -O 5000 &
xbacklight -set 20% &
xcompmgr 2>&1 >/dev/null &

# launch agent
eval $(/usr/bin/killall ssh-agent; /usr/bin/ssh-agent)

# xrdb - merge ~/.Xresources
# urxvtd --quiet --opendisplay --fork

#launch statusbar program
/home/langest/repos/dwmstatus-c/dwmstatus 2>&1 >/dev/null &

# disable beep
xset b off &

numlockx on
setxkbmap -option ctrl:nocaps

exec dwm
