#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

mpv --volume=60 downloads/WindowsXpStartupSound.mp4a &

xrandr --output HDMI2 --off &# --same-as LVDS1 --mode 1280x800
redshift 5000 &
xbacklight -set 30% &
xcompmgr &

# launch agent
eval $(/usr/bin/killall ssh-agent; /usr/bin/ssh-agent)

feh --randomize --recursive --bg-fill /home/langest/currentWps/
xrdb - merge ~/.Xresources
urxvtd --quiet --opendisplay --fork

#launch statusbar program
dwmstatus &

# disable beep
xset b off &

numlockx on
setxkbmap -option ctrl:nocaps

exec dwm
