#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

mpv --volume=90 'Windows XP Startup.mp3' &

#xrandr --output HDMI2 --off
#xrandr --output HDMI2 --same-as eDP1
#feh --randomize --recursive --bg-tile /home/langest/img/tiling

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

redshift -O 5000
xbacklight -set 30%
xcompmgr 2>&1 >/dev/null &

# launch agent
eval $(/usr/bin/killall ssh-agent; /usr/bin/ssh-agent)

xrdb -merge ~/.Xresources
# urxvtd --quiet --opendisplay --fork

/home/langest/repos/dwmstatus-c/dwmstatus 2>&1 >/dev/null &

# disable beep
xset b off

numlockx on
setxkbmap -option ctrl:nocaps

#/bin/bash -c 'sleep 1.92; xrandr --output HDMI1 --right-of eDP1 --auto --rotate left; xrandr --output HDMI2 --right-of HDMI1 --mode 1920x1200; xrandr --output eDP1 --off #; feh --randomize --recursive --bg-fill /home/langest/img/wps' &
xrandr --output HDMI1 --off
xrandr --output HDMI2 --off
feh --randomize --recursive --bg-fill /home/langest/img/wps

exec dwm
#exec start-lumina-desktop
