#!/bin/bash
#pacman
#alias pacmanclean='sudo pacman -Rns $(pacman -Qqtd)'
# '[r]emove [o]rphans' - recursively remove ALL orphaned packages
alias pacro="/usr/bin/pacman -Qtdq > /dev/null && sudo /usr/bin/pacman -Rns \$(/usr/bin/pacman -Qtdq | sed -e ':a;N;\$!ba;s/\n/ /g')"

#change wp
alias setwp='feh --bg-fill'

#watch images
alias fehshow='feh -rzFD5'

#display terminal colors
alias colors='sh ~/.colors.sh'

#mount
alias mountusb='sudo mount -o gid=users,fmask=113,dmask=002'
alias umnt='sudo umount'

#ssh
alias ssh2kth='ssh -X langest@u-shell.csc.kth.se'

#git
alias status='git status'
alias pull='git pull'
alias push='git push'
alias commit='git commit'
#alias diff='git diff' #cannot use this since I need the diff command
alias amend='git commit --amend'
alias checkout='git checkout'
alias merge='git merge'
alias prune='git pull origin --prune'
alias add='git add'

#c++
alias remake='make clean; make'

#urxvt
alias split='urxvtc'
alias urxvtmerge='xrdb -merge ~/.Xresources; killall urxvtd'

#wicd
alias wicdc='wicd-curses'

#transmission
alias starttransmission='sudo transmission-daemon'
alias stoptransmission='sudo transmission-remote --exit'

#reinstall dwm
alias reinstalldwm='cd ~/programming/dwm/dwm-6.0/ && sudo rm config.h && sudo make config.h && sudo make uninstall && sudo make install && cd'

#gource
alias gource='gource -i 0'
