#!/bin/bash

if [ -z "$MONITOR_SETTINGS" ]; then
	export MONITOR_SETTINGS=internal
fi
export MONITOR_SETTINGS=external
export GIT_HOME=$HOME/repos

xbacklight -set 30%

# launch agent
eval $(/usr/bin/killall ssh-agent; /usr/bin/ssh-agent)

xrdb -merge ~/.Xresources
urxvtd --quiet --opendisplay --fork

# numlockx on

# disable beep
xset b off

setxkbmap -option ctrl:nocaps

#SETUP_MOUSE=$GIT_HOME/dotfiles/scripts/mouse_config.sh
#if [[ -x "$SETUP_MOUSE" ]]; then
#	/bin/bash ${SETUP_MOUSE}
#fi

SETUP_SCREENS=$GIT_HOME/dotfiles/scripts/setup_screens.sh
if [[ -x "$SETUP_SCREENS" ]]; then
	/bin/bash ${SETUP_SCREENS}
fi

exec i3
